import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { SidebarProvider } from '@/components/ui/sidebar';
import { GlobalsProvider } from '@/modules/globals/GlobalsProvider';

import './globals.css';

import { AppSidebar } from '@/app/_sidebar/AppSidebar';
import { cn } from '@/lib/utils';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable, 'dark antialiased')}>
        <GlobalsProvider>
          <SidebarProvider>
            <AppSidebar />
            {children}
          </SidebarProvider>
        </GlobalsProvider>
      </body>
    </html>
  );
}
